# Generated by Django 3.2.7 on 2021-10-22 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_profile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='username',
            field=models.CharField(blank=True, editable=False, max_length=200, null=True),
        ),
    ]
